Repository microsoft/react-native-windows-samples, pull requests merged in 2021-03, with the labels that each got.

#405 Update fix-unbroken.js to load existing file, add PR to check file is up to date
  .github/scripts/CheckUnbrokenExclusions.ps1
  .github/workflows/website-pr.yml
  website/.unbroken_exclusions
  website/fix-unbroken.js
Labels: AutoMerge

#384 Update docs to point to react-native-macos 0.63 as latest
  docs/rnm-getting-started.md
  website/versioned_docs/version-0.63/rnm-getting-started.md
Labels: AutoMerge, version 0.64

#413 Update CameraDemo to 0.64
  samples/CameraDemo/.flowconfig
  samples/CameraDemo/.gitattributes
  samples/CameraDemo/.prettierrc.js
  samples/CameraDemo/README.md
  samples/CameraDemo/_editorconfig
  samples/CameraDemo/android/app/build.gradle
  samples/CameraDemo/android/app/src/debug/AndroidManifest.xml
  samples/CameraDemo/android/app/src/main/AndroidManifest.xml
  samples/CameraDemo/android/app/src/main/res/values/styles.xml
  samples/CameraDemo/android/build.gradle
  samples/CameraDemo/android/gradle.properties
  samples/CameraDemo/android/gradle/wrapper/gradle-wrapper.jar
  samples/CameraDemo/android/gradle/wrapper/gradle-wrapper.properties
  samples/CameraDemo/android/gradlew
  samples/CameraDemo/android/gradlew.bat
  samples/CameraDemo/ios/CameraDemo-tvOS/Info.plist
  samples/CameraDemo/ios/CameraDemo-tvOSTests/Info.plist
  samples/CameraDemo/ios/CameraDemo.xcodeproj/project.pbxproj
  samples/CameraDemo/ios/CameraDemo.xcodeproj/xcshareddata/xcschemes/CameraDemo-tvOS.xcscheme
  samples/CameraDemo/ios/CameraDemo.xcodeproj/xcshareddata/xcschemes/CameraDemo.xcscheme
  samples/CameraDemo/ios/CameraDemo/AppDelegate.m
  samples/CameraDemo/ios/CameraDemo/Info.plist
  samples/CameraDemo/ios/CameraDemo/LaunchScreen.storyboard
  samples/CameraDemo/ios/Podfile
  samples/CameraDemo/metro.config.js
  samples/CameraDemo/package.json
  samples/CameraDemo/windows/CameraDemo.sln
  samples/CameraDemo/windows/CameraDemo/App.cpp
  samples/CameraDemo/windows/CameraDemo/App.h
  samples/CameraDemo/windows/CameraDemo/AutolinkedNativeModules.g.h
  samples/CameraDemo/windows/CameraDemo/AutolinkedNativeModules.g.props
  samples/CameraDemo/windows/CameraDemo/CameraDemo.vcxproj
  samples/CameraDemo/windows/CameraDemo/CameraDemo_TemporaryKey.pfx
  samples/CameraDemo/windows/CameraDemo/MainPage.cpp
  samples/CameraDemo/windows/CameraDemo/MainPage.h
  samples/CameraDemo/windows/CameraDemo/ReactPackageProvider.cpp
  samples/CameraDemo/windows/CameraDemo/ReactPackageProvider.h
  samples/CameraDemo/windows/CameraDemo/pch.h
  samples/CameraDemo/windows/ExperimentalFeatures.props
  samples/CameraDemo/yarn.lock
Labels: AutoMerge

#376 Blog update 0.64
  website/blog/2021-03-16-64updates.md
  website/blog/assets/gallery_demo_1.gif
  website/blog/assets/janeasystemslogo.png
Labels: version 0.64

#419 Update GetFolderSize.ps1
  .github/scripts/GetFolderSize.ps1
Labels: AutoMerge
